apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/bamboo-storm-467105-k9/locations/us-central1-c/clusters/cluster-dev

